### ISSUE TITLE
Does it work with ESP8266?

### ISSUE THREAD

**Issue by Dancopy** [jhonoryza/ESP32-RG-Display-HUB08#1]
Does it work with ESP8266 Nodemcu? If yes, what should be changed in the code? Thank you

**Comment by jhonoryza** [comment]
I haven't test it with esp8266, because it use more pin in esp32

**Comment by Dancopy** [comment]
Are the pins on your screen like in the drawing I'm sending you attached? Because in the 'demo.ino' example it shows different!
![HUB08 interface](https://user-images.githubusercontent.com/37884487/54061736-ef9c7a00-41e0-11e9-9f97-89686aa72617.jpg)
If you give me a hint of how I should connect, I thank you very much!

**Comment by cytrus77** [comment]
Hi,

@Dancopy did You get this worked?
I've got same pinout in my display but no success so far with esp8266.
Any help will be appreciated. Thanks

**Comment by jhonoryza** [comment]
sorry @Dancopy demo.ino is still from the origin code repo, i am not modified it, it can works with esp32 but i dont know if it is work with esp8266, i haven't tested it and it use alot of pins on esp32, i am not sure it will work in esp8266
